apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: j8ym49m1q-java-springboot
  janus-idp.io/tekton: j8ym49m1q-java-springboot
  backstage.io/kubernetes-id: j8ym49m1q-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: j8ym49m1q-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
